application: lapecdn
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

derived_file_type:
- python_precompiled

skip_files: 
- ^version$

handlers:

- url: /css
  static_dir: css
  
- url: /downloads
  static_dir: downloads
  
- url: /flash
  static_dir: flash
  
- url: /images
  static_dir: images

- url: /js
  static_dir: js
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
  
- url: /
  static_files: index.html
  upload: index.html